name: deploy-code

on:
  workflow_dispatch:
    inputs:
      vms:
        description: 'List of VM configurations'
        required: true
        default: |
          - host: vm1-host
            username: vm1-username
            password: vm1-password
          - host: vm2-host
            username: vm2-username
            password: vm2-password

jobs:
  set-up-vars:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        vm_index: [0, 1]
    steps:
      - name: Set up environment variables
        run: |
          VM_CONFIG=$(echo "${{fromJson(inputs.vms)}}" | jq -r ".[${{ matrix.vm_index }}]")
          VM_HOST=$(echo "$VM_CONFIG" | jq -r '.host')
          VM_USERNAME=$(echo "$VM_CONFIG" | jq -r '.username')
          VM_PASSWORD=$(echo "$VM_CONFIG" | jq -r '.password')
          echo "VM_HOST=$VM_HOST" >> $GITHUB_ENV
          echo "VM_USERNAME=$VM_USERNAME" >> $GITHUB_ENV
          echo "VM_PASSWORD=$VM_PASSWORD" >> $GITHUB_ENV

  deploy-on-vm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        vm_index: [0, 1]
    steps:
      - name: Execute commands on VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.VM_HOST }}
          username: ${{ env.VM_USERNAME }}
          password: ${{ env.VM_PASSWORD }}
          port: 22
          script: |
            if [ -d ${{ github.event.repository.name }} ]; then
              echo "exists"
              cd ${{ github.event.repository.name }}
              git pull
            else
              echo "doesnt exist"
              git clone https://github.com/${{ github.repository }}.git 
            fi
            sudo rm -r /etc/systemd/system/fastapi.service
            sudo cp /home/${{ env.VM_USERNAME }}/${{ github.event.repository.name }}/fastapi.service /etc/systemd/system/ 
            sudo sed -i "s|\${USER}|${{ env.VM_USERNAME }}|g" /etc/systemd/system/fastapi.service
            sudo sed -i "s|\${WORKING_DIRECTORY}|/home/${{ env.VM_USERNAME }}/${{ github.event.repository.name }}|g" /etc/systemd/system/fastapi.service
            cd ${WORKING_DIRECTORY}/home/${{ env.VM_USERNAME }}/${{ github.event.repository.name }}
            sudo apt update
            sudo apt install -y python3 python3-pip
            pip install -r requirements.txt
            cd /etc/systemd/system/
            sudo systemctl enable fastapi.service
            sudo systemctl daemon-reload
            sudo service fastapi start
