name: deploy-code

on:
  workflow_dispatch:
    inputs:
      vms:
        description: 'List of VM configurations'
        required: true
        default: |
          - host: vm1-host
            username: vm1-username
            password: vm1-password
          - host: vm2-host
            username: vm2-username
            password: vm2-password

env:
  VM_HOST_1: ${{fromJson(inputs.vms[0].host)}}
  VM_USERNAME_1: ${{fromJson(inputs.vms[0].username)}}
  VM_PASSWORD_1: ${{fromJson(inputs.vms[0].password)}}
  VM_HOST_2: ${{fromJson(inputs.vms[1].host)}}
  VM_USERNAME_2: ${{fromJson(inputs.vms[1].username)}}
  VM_PASSWORD_2: ${{fromJson(inputs.vms[1].password)}}

jobs:
  deploy-on-vm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        vm_index: [1, 2]

    steps:
      - name: Execute commands on VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env[format('VM_HOST_{0}', matrix.vm_index)] }}
          username: ${{ env[format('VM_USERNAME_{0}', matrix.vm_index)] }}
          password: ${{ env[format('VM_PASSWORD_{0}', matrix.vm_index)] }}
          port: 22
          script: |
            if [ -d ${{ github.event.repository.name }} ]; then
              echo "exists"
              cd ${{ github.event.repository.name }}
              git pull
            else
              echo "doesnt exist"
              git clone https://github.com/${{ github.repository }}.git 
            fi
            sudo rm -r /etc/systemd/system/fastapi.service
            sudo cp /home/${{ env.VM_USERNAME }}/${{ github.event.repository.name }}/fastapi.service /etc/systemd/system/ 
            sudo sed -i "s|\${USER}|${{ env.VM_USERNAME }}|g" /etc/systemd/system/fastapi.service
            sudo sed -i "s|\${WORKING_DIRECTORY}|/home/${{ env.VM_USERNAME }}/${{ github.event.repository.name }}|g" /etc/systemd/system/fastapi.service
            cd ${WORKING_DIRECTORY}/home/${{ env.VM_USERNAME }}/${{ github.event.repository.name }}
            sudo apt update
            sudo apt install -y python3 python3-pip
            pip install -r requirements.txt
            cd /etc/systemd/system/
            sudo systemctl enable fastapi.service
            sudo systemctl daemon-reload
            sudo service fastapi start
