name: deploy-code

on:
  push:
    branches: [main]

jobs:
  deploy-on-vm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        vm_index: [1, 2]

    steps:
      - name: Set up environment variables
        run: |
          echo ${{ secrets.AZURE_VM_PORT1 }}
          echo "VM_HOST=${{ secrets[format('AZURE_VM_HOST{0}', matrix.vm_index)] }}" >> $GITHUB_ENV
          echo "VM_USERNAME=${{ secrets[format('AZURE_VM_USERNAME_{0}', matrix.vm_index)] }}" >> $GITHUB_ENV
          echo "VM_PASSWORD=${{ secrets[format('AZURE_VM_PASSWORD{0}', matrix.vm_index)] }}" >> $GITHUB_ENV
          echo "VM_PORT=${{ secrets.AZURE_VM_PORT }}" >> $GITHUB_ENV

      - name: Execute commands on VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.VM_HOST }}
          username: ${{ env.VM_USERNAME }}
          password: ${{ env.VM_PASSWORD }}
          port: ${{ env.VM_PORT }}
          script: |
            if [ -d ${{ github.event.repository.name }} ]; then
              echo "exists"
              cd ${{ github.event.repository.name }}
              git pull
            else
              echo "doesnt exist"
              git clone https://github.com/${{ github.repository }}.git 
            fi
            sudo rm -r /etc/systemd/system/fastapi.service
            sudo cp /home/${{ env.VM_USERNAME }}/${{ github.event.repository.name }}/fastapi.service /etc/systemd/system/ 
            sudo sed -i "s|\${USER}|${{ env.VM_USERNAME }}|g" /etc/systemd/system/fastapi.service
            sudo sed -i "s|\${WORKING_DIRECTORY}|/home/${{ env.VM_USERNAME }}/${{ github.event.repository.name }}|g" /etc/systemd/system/fastapi.service
            cd ${WORKING_DIRECTORY}/home/${{ env.VM_USERNAME }}/${{ github.event.repository.name }}
            pip install -r requirements.txt
            cd /etc/systemd/system/
            sudo systemctl enable fastapi.service
            sudo systemctl daemon-reload
            sudo service fastapi start

