name: install-fastapi-code

on:
  push:
      tags:
      - 'install-fastapi-code'

jobs:
  deploy-on-vm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        vm_index: [1, 2, 3] 
    steps:
      - name: Set up environment variables
        run: |
          if [ ${{ matrix.vm_index }} -eq 1 ]; then
            echo "VM_HOST=40.76.184.13" >> $GITHUB_ENV
            echo "VM_USERNAME=fastapi-vm1" >> $GITHUB_ENV
            echo "VM_PASSWORD=Yael1234567890" >> $GITHUB_ENV
          elif [ ${{ matrix.vm_index }} -eq 2 ]; then
            echo "VM_HOST=20.55.100.106" >> $GITHUB_ENV
            echo "VM_USERNAME=fastapi-vm2" >> $GITHUB_ENV
            echo "VM_PASSWORD=Yael1234567890" >> $GITHUB_ENV
          elif [ ${{ matrix.vm_index }} -eq 3 ]; then
            echo "VM_HOST=172.178.85.40" >> $GITHUB_ENV
            echo "VM_USERNAME=fastapi-vm3" >> $GITHUB_ENV
            echo "VM_PASSWORD=Yael1234567890" >> $GITHUB_ENV
          fi
          echo "UPDATE_OR_INSTALL=${{ github.event.inputs.update_or_install }}" >> $GITHUB_ENV

      - name: Execute commands on VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.VM_HOST }}
          username: ${{ env.VM_USERNAME }}
          password: ${{ env.VM_PASSWORD }}
          port: 22
          script: |
            REPO_DIR="/home/${{ github.event.repository.name }}"
            echo "Repository does not exist, installing"
            cd /home/
            git clone https://github.com/${{ github.repository }}.git "$REPO_DIR"
            cd "$REPO_DIR"
            sudo mkdir logs
            sudo mkdir merged_files
            sudo chmod 777 logs
            sudo chmod 777 merged_files
            sudo chmod +x dependencies/install_packages.sh
            ./dependencies/install_packages.sh
            # Download and install Filebeat
            sudo wget -P /home/ https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.16.3-amd64.deb
            sudo dpkg -i /home/filebeat-7.16.3-amd64.deb
            sudo cp $REPO_DIR/dependencies/filebeat.yml /etc/filebeat/
            sudo systemctl restart filebeat
            sudo systemctl enable filebeat
            sudo cp "$REPO_DIR/dependencies/fastapi.service" /etc/systemd/system/
            sudo systemctl enable fastapi.service
            sudo sed -i "s|\${USER}|${{ env.VM_USERNAME }}|g" /etc/systemd/system/fastapi.service
            sudo sed -i "s|\${WORKING_DIRECTORY}|$REPO_DIR|g" /etc/systemd/system/fastapi.service
            cd "$REPO_DIR"
            python3 -m pip install -r requirements.txt
            sudo systemctl daemon-reload
            sudo systemctl restart fastapi
